template = "https://github.com/giellalt/template-lang-und"
rev_id = 264
template_sha = "120f384c016282eb1fbbcc762e0ac6064a37eb45"

[replacements]
__GLOTTOLOG_ID__ = "khak1248"
__REPO__ = "lang-kjh"
__UND2C__ = "kjh"
__UNDEFINED__ = "Khakas"
__UND__ = "kjh"
