template = "https://github.com/giellalt/template-lang-und"
rev_id = 255
template_sha = "b36832e6713c79f483aee143e866d6cad5dec90e"

[replacements]
__GLOTTOLOG_ID__ = "khak1248"
__REPO__ = "lang-kjh"
__UND2C__ = "kjh"
__UNDEFINED__ = "Khakas"
__UND__ = "kjh"
